config/routes.rb
MyStaticPages::Application.routes.draw do
  get "user_sessions/new"
  get "user_sessions/create"
  get "user_sessions/destroy"

  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  get 'logout' => 'user_sessions#destroy'

  resources :users

  resources :todos

  resources :pages
  root 'todos#index'
  match "search", to: "todos#search", via: 'post'
  match "search", to: "todos#index", via: 'get'
  match "welcome", to: "pages#welcome", via: 'get'
  match "about",   to: "pages#about",   via: 'get'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	before_filter :require_login

	def index
		redirect_to pages_path
	end

	private
	def not_authenticated
	  redirect_to login_path, alert: "Please login first"
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :set_todo, only: [:show, :edit, :update, :destroy]
  def welcome
  end

  def about
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.paginate(:page => params[:page], :per_page => 12)
    require 'github-markup'
  #TODO: implement usage of markup
  end

  # POST /search/
  def search
    if params[:search].nil? || params[:search].empty? then
      @todos = Todo.paginate(:page => params[:page], :per_page => 12)
    else
      @todos = Todo.paginate(:conditions => ["name LIKE ?", "%" + params[:search] + "%"], :page => params[:page], :per_page => 12)
    end
    render 'index'
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todo }
      else
        format.html { render action: 'new' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:name, :description, :image, :remote_image_url)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
 
  skip_before_filter :require_login, except: [:destroy]
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:users, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to '/', notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  skip_before_filter :require_login, only: [:index, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

      if @user.save
        redirect_back_or_to(:users, notice: 'Login successful')
      else
        flash.now[:alert] = 'Login failed'
        render action: 'new'
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

def title(content)
  content_for(:title, content)
end

def page_title
  delimiter = "| "
  if content_for?(:title)
    "#{delimiter}#{content_for(:title)}"
  end
end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moje strony <%= page_title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="nav" class="navigation-bar">
    <% if current_user %>
      <%= link_to "Edytuj profil", edit_user_path(current_user.id) %>
      <%= link_to "Wyloguj", :logout, method: :post %>
    <% else %>
      <%= link_to "Rejestracja", new_user_path %> |
      <%= link_to "Logowanie", :login %>
    <% end %>
  </div>
  <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>
  <%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<% title 'About Us' %>
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/welcome.html.erb
<% title 'Welcome' %>
<h1>Pages#welcome</h1>
<p>Find me in app/views/pages/welcome.html.erb</p>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<br/>

app/views/todos/_search.html.erb
<%= form_tag("/search", method: "post") do %>
  <%= label_tag(:search, "Search for:") %>
  <%= text_field_tag(:search) %>
  <%= submit_tag("Search") %>
<% end %>
<br/>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>
<div class="center form">
	<%= render 'form' %>

	<span class="formbutton"><%= link_to 'Wyświetl', @todo %> |</span>
	<span class="formbutton"><%= link_to 'Powrót', todos_path %></span>
</div>

app/views/todos/index.html.erb
<h1>Moja lista rzeczy do zrobienia</h1>
<span class="formbutton"><%= link_to 'Dodaj nowe zadanie', new_todo_path %></span>
<span class="formbutton"><%= link_to 'O nas', controller: 'pages', action: 'about' %></span>
<span class="formbutton"><%= link_to 'Welcome!', controller: 'pages', action: 'welcome' %></span>
<span class="search-engine"><%= render 'search' %></span>

  <div id="content">
    <% @todos.each do |todo| %>
      <div class="item">
        <div class="item-content">
          <p class="item-title"><%= todo.name %></p>
          <p class="item-desc"><%= todo.description %></p>
          <span class="formbutton"><%= link_to 'Wyświetl', todo %></span>
          <span class="formbutton"><%= link_to 'Edytuj', edit_todo_path(todo) %></span>
          <span class="formbutton"><%= link_to 'Usuń', todo, method: :delete, data: { confirm: 'Jesteś pewien?' } %></span>
        </div>
      </div>
    <% end %>
  </div>
<br>
<%= will_paginate @todos %>
<script>
$( document ).ready(function() {
    var $container = $('#content');
    
    $container.isotope({
      animationEngine : 'jquery',
      itemSelector: '.item'
    });

    $container.infinitescroll({
      navSelector  : ".pagination",            
                     // selector for the paged navigation (it will be hidden)
      nextSelector : ".next_page",    
                     // selector for the NEXT link (to page 2)
      itemSelector : ".item",
        loading: {
            finishedMsg: 'No more pages to load.',
            img: 'http://i.imgur.com/qkKy8.gif'
          }
        },
        // call Isotope as a callback
        function( newElements ) {
          $container.isotope( 'appended', $( newElements ) ); 
        }
      );
  }); 
</script>

app/views/todos/new.html.erb
<h1>Nowa notatka</h1>

<div class="center form">
	<%= render 'form' %>
	<span class="formbutton"><%= link_to 'Powrót', pages_path %></span>
</div>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show formbutton">
	<p>
	  <strong>Tytuł:</strong>
	  <%= @todo.name %>
	</p>

	<p>
	  <strong>Opis:</strong>
	  <%= @todo.description %>
	</p>

	<p>
		<%= image_tag @todo.image %>
	</p>

	<%= link_to 'Edycja', edit_todo_path(@todo) %> |
	<%= link_to 'Powrót', todos_path %>
</div>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag 'Adres email' %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag 'Hasło' %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Zaloguj" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Logowanie</h1>

<div class="login-menu">
	<%= render 'form' %>
</div>

app/views/users/_form.html.erb
<div class="login-menu">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'email' %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label 'Hasło' %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label 'Potwierdź hasło' %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Powrót', todos_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= user.salt %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Rejestracja</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @user.crypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>